name: wireapps_technical_test
description: WIREAPPS Technical test

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  dio: ^4.0.0
  flutter_staggered_animations: ^1.0.0
  shimmer: ^2.0.0
  path_provider: ^2.0.9
  auto_route: ^3.2.4
  flutter_native_splash: ^2.1.6

  #Bloc supported plugins
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  hydrated_bloc: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
