class CommonStrings {
  static const appTitle = 'Elegent Media Practical Assignment';
  static const back = 'Back';
  static const next = "Next";
  static const continues = "Continue";
  static const submit ="Submit";
  static const gettingThingsReady= "Getting things ready";
  static const pleaseWait="Please wait";
  static const cancel = "Cancel";
  static const no="No";
  static const yes="Yes";
  static const save="Save";
  static const areYouSureContinue="Are you sure continue?";
  static const ok="Ok";
  static const thisActionCannotBeUndone="This action cannot be undone";
  static const today="Today";
  static const last="Last";
  static const total="Total";
  static const fetchingData="Fetching data";
  static const noInternetConnection="No internet connection";
  static const pleaseTurnOnTheInternetConnection="Please turn on the internet connection";
  static const checkInternet="Check internet";
  static const retry="Retry";
  static const areYouSureWantToExit="Are you sure want to exit?";
  static const send="Send";
  static const welcome="Welcome";
  static const firstTimeUser="First time user?";
  static const changeTheme="Change theme";
}
